remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

baseurl: cante.ole

collections:
  easy:
    output: true
    permalink: /:collection/:name/
  intermediate:
    output: true
    permalink: /:collection/:name/
  difficult:
    output: true
    permalink: /:collection/:name/
